name: Release

on:
  workflow_dispatch:
    inputs:
      scope:
        description: "Version bump scope (patch, minor, major)"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      RELEASE_SCOPE: ${{ github.event.inputs.scope }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: https://registry.npmjs.org
      - name: Setup Git
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git remote rm origin
          git remote add origin https://pierre-cm:${GITHUB_TOKEN}@github.com/pierre-cm/prompteur.git
          git symbolic-ref HEAD refs/heads/main
      - name: Install dependencies
        run: npm ci
      - name: Release
        run: |
          npm run release -- --increment $RELEASE_SCOPE --ci
